name: Check mkdocs build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UV_VERSION: 0.6
  PYTHON_VERSION: 3.12

jobs:
  mkdocs-build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check mkdocs build
        run: uv run --with 'nomad-lab[dev]' mkdocs build
