name: Sync GitLab NOMAD-FAIR Docs

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 10 * * 1-5'  # UTC

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo (main branch)
      uses: actions/checkout@v4
      # Keep some commits on `nomad-docs`
      with:
        ref: '76401a8b524f229ebee2cf0f3f723cd219c2e9ae'

    - name: Sparse-checkout only 'docs/' from GitLab repo
      run: |
        GITLAB_REPO="https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git"

        # Clone the repo with sparse-checkout to only get 'docs/'
        git clone --filter=blob:none --no-checkout --branch develop "$GITLAB_REPO" gitlab-temp
        cd gitlab-temp
        git sparse-checkout init --cone
        git sparse-checkout set docs
        git checkout

    - name: Rsync 'docs/' into current repo
      run: |
        rsync -av --delete gitlab-temp/docs/ docs/

    - name: Check for Changes
      id: check-changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: ${{ steps.check-changes.outputs.changed == 'true' }}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update docs"
        title: "Update docs"
        body: "This pull request updates docs."
        branch: update-docs
        base: main
